services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - ./config/:/var/jenkins_home
    ports:
      - 8080:8080
    restart: always

  ssh-agent:
    image: jenkins/ssh-agent
    container_name: jenkins-ssh-agent
    environment:
      - JENKINS_AGENT_SSH_PUBKEY=<public_key>
    restart: always

networks:
  default:
    name: reverseproxy_nw
    external: true
