services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    volumes:
      - ./config/:/var/jenkins_home
    ports:
      - 8080:8080
    restart: always

networks:
  default:
    name: reverseproxy_nw
    external: true
