---
- name: Install python3-pip
  ansible.builtin.apt:
    name:
      - python3-pip

- name: Install pipx
  ansible.builtin.apt:
    name:
      - pipx

- name: Install powerline-shell
  become: true
  become_user: "{{ user }}"
  community.general.pipx:
    name: powerline-shell
  register: output
  changed_when: output.changed == true

- name: Install exa
  ansible.builtin.apt:
    name:
      - exa

- name: Install Zsh
  ansible.builtin.apt:
    name:
      - zsh

- name: Copy .zsh_aliases file
  ansible.builtin.copy:
    src: files/dotfiles/.zsh_aliases
    dest: /home/{{ user }}/
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0644"

- name: Copy .zshrc file
  ansible.builtin.copy:
    src: files/dotfiles/.zshrc
    dest: /home/{{ user }}/
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0644"

- name: Make .zsh-plugins directory
  ansible.builtin.file:
    path: /home/{{ user }}/.zsh-plugins
    state: directory
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: "0744"

- name: Copy .zsh-plugins
  ansible.builtin.copy:
    src: files/dotfiles/.zsh-plugins
    dest: /home/{{ user }}/
    owner: root
    group: root
    mode: "0644"

- name: Change default root shell to Zsh
  ansible.builtin.command: chsh -s /bin/zsh root
  register: output
  changed_when: "'Shell changed' in output.stdout"

- name: Change default user shell to Zsh
  ansible.builtin.command: chsh -s /bin/zsh {{ user }}
  register: output
  changed_when: "'Shell changed' in output.stdout"
