---
- name: Install python3-pip
  ansible.builtin.apt:
    name:
      - python3-pip

- name: Install pipx
  ansible.builtin.apt:
    name:
      - pipx

- name: Install powerline-shell
  become: true
  become_user: lowie
  community.general.pipx:
    name: powerline-shell
  register: output
  changed_when: output.changed == true

- name: Install exa
  ansible.builtin.apt:
    name:
      - exa

- name: Copy .bash_aliases file
  ansible.builtin.copy:
    src: ../files/dotfiles/.bash_aliases
    dest: /home/lowie/
    owner: lowie
    group: lowie
    mode: "0644"

- name: Copy .bashrc file
  ansible.builtin.copy:
    src: ../files/dotfiles/.bashrc
    dest: /home/lowie/
    owner: lowie
    group: lowie
    mode: "0644"
